# Data Preprocessing

In [72]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Remove the scientific notation in np.array
np.set_printoptions(precision=1)

In [73]:
# Importing the dataset
dataset = pd.read_csv('Data.csv')
dataset

Country  Age  Salary Purchased
0   France 44.0 72000.0        No
1    Spain 27.0 48000.0       Yes
2  Germany 30.0 54000.0        No
3    Spain 38.0 61000.0        No
4  Germany 40.0     nan       Yes
5   France 35.0 58000.0       Yes
6    Spain  nan 52000.0        No
7   France 48.0 79000.0       Yes
8  Germany 50.0 83000.0        No
9   France 37.0 67000.0       Yes

In [74]:
# Manually split the dataset into the training set and test set
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [75]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [76]:
# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

/Users/zhangyinghao/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [77]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# LabelEncoder will encode the categorical variable into the ordered number
labelEncoder_X = LabelEncoder()
X[:, 0] = labelEncoder_X.fit_transform(X[:, 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [80]:
# OneHotEncoder will encode the categorical variable into the dummy variable
oneHotEncoder_X = OneHotEncoder(categorical_features=[0])
X = oneHotEncoder_X.fit_transform(X).toarray()
X

/Users/zhangyinghao/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/zhangyinghao/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[    0. ,     1. ,     0. ,     0. ,    44. , 72000. ],
       [    1. ,     0. ,     0. ,     1. ,    27. , 48000. ],
       [    1. ,     0. ,     1. ,     0. ,    30. , 54000. ],
       [    1. ,     0. ,     0. ,     1. ,    38. , 61000. ],
       [    1. ,     0. ,     1. ,     0. ,    40. , 63777.8],
       [    0. ,     1. ,     0. ,     0. ,    35. , 58000. ],
       [    1. ,     0. ,     0. ,     1. ,    38.8, 52000. ],
       [    0. ,     1. ,     0. ,     0. ,    48. , 79000. ],
       [    1. ,     0. ,     1. ,     0. ,    50. , 83000. ],
       [    0. ,     1. ,     0. ,     0. ,    37. , 67000. ]])

In [81]:
labelEncoder_y = LabelEncoder()
y = labelEncoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [82]:
# Automatically split the dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

There are two types of feature scaling:
- Standardization:
$$x_{\text{stand}}=\frac{x-\text{mean}(x)}{\text{standard deviation}(x)}$$
- Normalization:
$$x_{\text{norm}}=\frac{x-\min(x)}{\max(x)-\min(x)}$$

In [83]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [84]:
X_train

array([[ 1. , -1. ,  2.6, -0.8,  0.3,  0.1],
       [-1. ,  1. , -0.4, -0.8, -0.3,  0.5],
       [ 1. , -1. , -0.4,  1.3, -2. , -1.5],
       [ 1. , -1. , -0.4,  1.3,  0.1, -1.1],
       [-1. ,  1. , -0.4, -0.8,  1.6,  1.7],
       [ 1. , -1. , -0.4,  1.3, -0.1, -0.2],
       [-1. ,  1. , -0.4, -0.8,  1. ,  1. ],
       [-1. ,  1. , -0.4, -0.8, -0.6, -0.5]])

In [85]:
X_test

array([[ 1. , -1. ,  2.6, -0.8, -1.5, -0.9],
       [ 1. , -1. ,  2.6, -0.8,  2. ,  2.1]])